// Code Generated by Sidekick is for learning and experimentation purposes only.
// filename: decode-ways-space-optimized.java
class Solution {
    public int numDecodings(String s) {
        int n = s.length();

        // next1 = dp[i + 1]
        // next2 = dp[i + 2]
        // We start from the end:
        // dp[n] = 1 -> empty suffix has one valid decoding
        int next1 = 1;
        int next2 = 0;

        // Fill from right to left
        for (int i = n - 1; i >= 0; i--) {
            int curr = 0;

            // A substring starting with '0' cannot be decoded
            if (s.charAt(i) != '0') {
                // Option 1: take one digit
                curr = next1;

                // Option 2: take two digits if valid
                if (i + 1 < n) {
                    int num = Integer.parseInt(s.substring(i, i + 2));
                    if (num >= 10 && num <= 26) {
                        curr += next2;
                    }
                }
            }

            // Shift the DP window:
            // next2 becomes old next1, next1 becomes current dp[i]
            next2 = next1;
            next1 = curr;
        }

        return next1;
    }
}
